spring:
  config:
    import: application-common.yml
  jackson:
    default-property-inclusion: non_null

snutt:
  secret-key:

springdoc:
  paths-to-match: /v1/**
  pre-loading-enabled: true
  pre-loading-locales: ko-KR,en-US
---
spring:
  config:
    activate:
      on-profile: dev
  mongodb:
    uri:
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  mongodb:
    uri:
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
