spring:
  config:
    import: application-common.yml
  jackson:
    default-property-inclusion: non_null

snutt:
  secret-key:

springdoc:
  paths-to-match: /v1/**
  pre-loading-enabled: true
  pre-loading-locales: ko-KR,en-US

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health-check
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri:
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri:
