spring:
  config:
    import: application-common.yml
  jackson:
    default-property-inclusion: non_null

snutt:
  secret-key:

springdoc:
  pre-loading-enabled: true
  pre-loading-locales: ko-KR,en-US
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri:
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri:
