spring:
  config:
    import: application-common.yml
  jackson:
    default-property-inclusion: non_null

snutt:
  secret-key:

springdoc:
  packages-to-scan: com.wafflestudio.snutt
  pre-loading-enabled: true
  pre-loading-locales: ko_KR,en_US,en_KR
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri:
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri:
