spring:
  config:
    import: application-common.yml
  batch:
    job:
      name: ${job.name:EMPTY}
  main:
    web-application-type: none
  task:
    scheduling:
      pool:
        size: 0
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
