spring:
  profiles:
    default: local
  mongodb:
    uri:
  data:
    redis:
      repositories:
        enabled: false
      host:
      database:

google:
  firebase:
    project-id:
    service-account:
    api-key:
    ios:
      bundle-id:
    dynamic-link:
      domain-uri-prefix:
      link-prefix:
      android:
        package-name:
      ios:
        bundle-id:
        app-store-id:

http:
  response-timeout: 3s

github:
  feedback:
    token:
    repo:
      owner:
      name:

api:
  server:
    snuttev:
      base-url: http://snutt-ev-api-dev.wafflestudio.com

secret-names: dev/snutt-timetable

---

spring:
  config:
    activate:
      on-profile: local
logging:
  config: classpath:logback/local.xml

---

spring:
  config:
    activate:
      on-profile: dev
  mongodb:
    uri:
    auto-index-creation: true
  data:
    redis:
      host:
      database:

google:
  firebase:
    project-id:
    service-account:
    api-key:
    ios:
      bundle-id:
    dynamic-link:
      domain-uri-prefix:
      link-prefix:
      android:
        package-name:
      ios:
        bundle-id:
        app-store-id:

api:
  server:
    snuttev:
      base-url: http://snutt-ev.snutt-dev.svc.cluster.local
      read-timeout: 5000

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod
  mongodb:
    uri:
  data:
    redis:
      host:
      database:

google:
  firebase:
    project-id:
    service-account:
    api-key:
    ios:
      bundle-id:
    dynamic-link:
      domain-uri-prefix:
      link-prefix:
      android:
        package-name:
      ios:
        bundle-id:
        app-store-id:

api:
  server:
    snuttev:
      base-url: http://snutt-ev.snutt-prod.svc.cluster.local
      read-timeout: 5000

secret-names: prod/snutt-timetable
