name: Deploy-batch-prod-native

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-native.yml
    with:
      ecr_repository: snutt-prod/snutt-timetable-batch
      dockerfile: batch/Dockerfile-native
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
