name: Deploy-api-dev-native

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-native.yml
    with:
      ecr_repository: snutt-dev/snutt-timetable
      dockerfile: api/Dockerfile-native
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
